---
title: "2_Lab_Introduction_to_R"
author: "Tim Yang"
date: '2022-09-06'
output: pdf_document
---

## 2. 3. 1 Basic Commands

```{r}
x <- c(1, 3, 2, 5)
x
```


```{r}
x = c(1, 6, 2)
x
```

```{r}
y = c(1, 4, 3)
```


```{r}
length(x)
length(y)
x + y
```

```{r}
ls()
rm(x, y)
ls()
```

```{r}
rm(list = ls())
```

```{r}
?matrix
```

```{r}
x <- matrix(data = c(1, 2, 3, 4), nrow = 2, ncol = 2)
x
```

```{r}
x <- matrix(c(1, 2, 3, 4), 2, 2)
```

```{r}
matrix(c(1, 2, 3, 4), 2, 2, byrow = TRUE)
```

```{r}
sqrt(x)
```

```{r}
x^2
```


```{r}
x <- rnorm(50)
y <- x + rnorm(50, mean = 50, sd = .1)
cor(x, y)
```

```{r}
set.seed(1303)
rnorm(50)
```

```{r}
set.seed(3)
y <- rnorm(100)
mean(y)
var(y)
sqrt(var(y))
sd(y)
```

## 2. 3. 2 Graphics

```{r}
x <- rnorm(100)
y <- rnorm(100)
plot(x, y)
```


```{r}
plot(x, y, xlab = "this is the x-axis", ylab = "this is the y-axis",
     main = "plot of X vs Y")
```


```{r}
x <- seq(1, 10)
x
```


```{r}
x <- 1:10
x
```

```{r}
x <- seq(-pi, pi, length = 50)
x
```


```{r}
y <- x
f <- outer(x, y, function(x, y) cos(y) / (1 + x^2))

contour(x, y, f)
```


```{r}
fa <- (f - t(f)) / 2
contour(x, y, fa, nlevels = 15)
```


```{r}
image(x, y, fa)
```


```{r}
persp(x, y, fa)
```


```{r}
persp(x, y, fa, theta = 30)
```


```{r}
persp(x, y, fa, theta = 30, phi = 70)
```

## 2. 3. 3 Indexing Data

```{r}
A <- matrix(1:16, 4, 4)
A
```


```{r}
A[2, 3]
```


```{r}
A[c(1, 3), c(2, 4)]
```


```{r}
A[1:3, 2:4]
```


```{r}
A[1:2, ]
```


```{r}
A[, 1:2]
```


```{r}
A[1, ]
```


```{r}
A[-c(1, 3), ]
```

```{r}
A[-c(1, 3), -c(1, 3, 4)]
```


```{r}
dim(A)
```

## 2. 3. 4 Loading Data

```{r}
# install.packages("ISLR2")
library(ISLR2)
```


```{r}
# View(Auto)
```


```{r}
head(Auto)
```


```{r}
dim(Auto)
```


```{r}
Auto <- na.omit(Auto)
dim(Auto)
```


```{r}
colnames(Auto)
```

## 2. 3. 5 Additional Graphical and Numerical Summaries

```{r}
plot(Auto$cylinders, Auto$mpg)
```


```{r}
attach(Auto)
plot(cylinders, mpg)
```


```{r}
cylinders <- as.factor(cylinders)
```


```{r}
plot(cylinders, mpg, col = "red", varwidth = T)
```

```{r}
plot(cylinders, mpg, col = "red", varwidth = T, horizontal = T)
```


```{r}
hist(mpg)
```


```{r}
hist(mpg, col = 2, breaks = 15)
```


```{r}
pairs(Auto)
```


```{r}
pairs(~ mpg + displacement + horsepower + weight + acceleration, data = Auto)
```


```{r}
plot(horsepower, mpg)
```

```{r}
# identify(horsepower, mpg, name)
```


```{r}
summary(Auto)
```


```{r}
summary(mpg)
```


```{r}
```


```{r}
```

